### ISSUE TITLE
Record types

### ISSUE THREAD

**Issue by anilkulkarni87** [speedment/avro-mocker#3]
Unfortunately i am unable to post the schema here , But i am getting the below error:

```
Exception in thread "main" java.lang.IllegalArgumentException: The avro type 'record' is currently not supported.
	at com.speedment.avromocker.mocker.MockerBuilderUtil.parseField(MockerBuilderUtil.java:94)
	at com.speedment.avromocker.mocker.MockerBuilderUtil.parseUnionField(MockerBuilderUtil.java:614)
	at com.speedment.avromocker.mocker.MockerBuilderUtil.parseField(MockerBuilderUtil.java:92)
	at com.speedment.avromocker.Main.main(Main.java:92)
```

**Comment by Pyknic** [comment]
Yes, we have not added support for mocking inner records yet. The types that are supported can be seen in [this file](https://github.com/speedment/avro-mocker/blob/master/src/main/java/com/speedment/avromocker/mocker/MockerBuilderUtil.java#L79). Feel free to contribute that if you want to!
